const HOOK__AFTER_LOGIN = 'AFTER_LOGIN';
const HOOK__BEFORE_LOGIN = 'BEFORE_LOGIN';
const FILTER_HOOK__LOGIN_URL = 'FILTER_HOOK_LOGIN_URL'
const AUTH = "auth"

export default { HOOK__AFTER_LOGIN, HOOK__BEFORE_LOGIN,FILTER_HOOK__LOGIN_URL, AUTH }